### PR TITLE
Jetty version 9.2.11.v20150529

### PR DESCRIPTION
**Pull request by gutobortolozzo**
Update of jetty version from 9.0.2.v20130417 to 9.2.11.v20150529. This new version come with javax.servlet-api:3.1, better startup time, ThreadPool bugs fixed and other improvements that can be found here [Jetty 9.2.11 Roadmap](http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/VERSION.txt?id=jetty-9.2.11.v20150529).

@perwendel Can you validate these changes please?

### CODE REVIEW

**Comment by jkwatson** [comment]
This looks good to me.  There are some formatting inconsistencies in a few of the files, but that looks like it pre-dates this PR.  :+1:

**Comment by gutobortolozzo** [comment]
@jkwatson, thanks for advice about the formatting inconsistencies. One other point about this PR is the jetty-version 9.3. As soon as this version become available I will submit one other PR with this new version that will support HTTP/2. For now all interfaces with jetty are compatible.

**Comment by r1j0** [comment]
PR looks fine. :+1:

**Comment by perwendel** [comment]
I will have a look at this after my vacation (the week after next)

**Comment by joakime** [comment]
Jetty 9.3.2 was just released today (btw)

**Comment by perwendel** [comment]
Thanks for contributing.
Try to format your code with the format settings in https://github.com/perwendel/spark/blob/master/config/spark-formatter-intellij.jar
to reduce risk of merge problems etc.

**Pull request merged**
