### PR TITLE
Enable passing WebSocket handler instances.

### PR DESCRIPTION
**Pull request by jakaarl**
Added a Spark.webSocket() method which accepts a handler instance
instead of a class. See issue #367.

### CODE REVIEW

**Comment by jakaarl** [comment]
This is a quickly hacked up change I made and very briefly tested. Definitely needs to be reviewed by someone "in the know" and properly tested.

**Comment by perwendel** [comment]
Looks good. Will review it more thoroughly ASAP.

**Comment by jvtrigueros** [comment]
This would be really awesome to have! I'm currently running into this issue.

**Comment by jakaarl** [comment]
I've looked a bit more into the code. The whole `WebSocketCreatorFactory` and `WebSocketCreator` thing does seem like unnecessary complexity, but since the latter is required by Jetty, there isn't that much to be achieved by refactoring. Also, my changes don't change thread safety of the web socket handlers: they are instantiated beforehand (at `ignite` before the changes and immediately after my changes) and the same instance serves all requests to the path.

**Comment by jpthiery** [comment]
Hi,
I encount the same issue. I need to have interaction with other collaborator of my WebSocket instance which need to get arguments in it.

Thanks for your help.

**Comment by cbeust** [comment]
It looks like this didn't get merged? (not seeing it in `spark-core:2.5`). Why not?

It would be really useful to specify the instance of the websocket handler instead of the class (in my case, this instance is injected by Guice so I want to pass my own instance instead of Spark calling `newInstance()` on the class.

**Comment by jakaarl** [comment]
I drew the conclusion that contributions are not welcome after my PR was in limbo for four months or something to that effect. Closed the PR.

**Comment by cbeust** [comment]
That's unfortunate :-(

**Pull request closed without merging**
