### PR TITLE
Enhancement: concept of "finally" filter

### PR DESCRIPTION
**Pull request by MouettE-SC**
Original work from @gutobortolozzo on PR 406
adapted for current spark tree

This updated PR shares the goal of PR #217 and #406 and fixes issues #195 and #324

### CODE REVIEW

**Comment by MouettE-SC** [comment]
This updated PR fixes #195 and #324

**Comment by basdek** [comment]
LGTM :+1:

**Comment by JWGmeligMeyling** [comment]
LGTM 👍

**Comment by kodfodrasz** [comment]
Meanwhile I ported my app to JAX-RS. Probably you should also do that. Jersey is very nice!

**Comment by MouettE-SC** [comment]
Related to #577

**Comment by AzureusNation** [comment]
I don't know about you @tipsy but couldn't this be added in to the event/callback system I am currently working on?

**Comment by JWGmeligMeyling** [comment]
This feature has been requested for years with quite a few reasonable implementations for it: just hit that green button. In the mean time, people should use JAX-RS. Resteasy is a pretty easy to set up framework with a reasonably small footprint. Plays nice with Jetty as well.

**Comment by perwendel** [comment]
I like this concept. However, the name `afterFinally` isn't good. The problem of course is that `finally` is a keyword. Me and @tipsy has been discussing a bit on possible names like:

`lastly`
`fynally`
`phinally`
`finalli`

etc. What do you guys think. Any proposals?

**Comment by gutobortolozzo** [comment]
When I submitted the P.R `afterFinally` was meant to be a temporary name. 
Well, I would choose `lastly` but also suggest `afterAll` since it's a very spread concept from other frameworks.

**Comment by MouettE-SC** [comment]
What about `done()` ?

**Comment by MouettE-SC** [comment]
Or we could use `complete()` or `completed()`, jquery-style

**Comment by tipsy** [comment]
Since you mentioned jQuery, maybe `always()` is an option?

**Comment by MouettE-SC** [comment]
I like `always()`. I can quickly add a commit to the PR, just need confirmation.

**Comment by MouettE-SC** [comment]
So we have a couple of fairly good choices :
```
always()      <- this one actually make sense along with before() and after()
done()        <- this one emphasizes more on the order than always()
lastly()
complete()
completed()
```
@perwendel what do you prefer so we can amend and merge this PR ?

**Comment by MouettE-SC** [comment]
Updated PR to the current tree and renamed filter to `done()`, for your consideration.

**Comment by MouettE-SC** [comment]
Requested in issue #715

**Comment by MouettE-SC** [comment]
Updated PR to the current tree (necessary following custom error pages modification)

**Comment by ph-hs** [comment]
The PR introduces done(..) but it is being executed before MatcherFilter is truly done. For example #712 highlights that status '200' is attached to resources sought that will end up as '404' (18 lines further down in MatcherFilter), and done(..) as per the PR is still showing response.status() as 200 :-(

**Comment by javiercanillas** [comment]
What is missing to merge this code on a new version?

**Comment by MouettE-SC** [comment]
@ph-hs thanks for your input, I moved the done filters call at the end of MatcherFilter.doFilter(). I kept this code afterwards because it seemed to make sense :

```
        } finally {
            try {
                DoneFilters.execute(context);
            } catch (Exception generalException) {
                GeneralError.modify(
                        httpRequest,
                        httpResponse,
                        body,
                        requestWrapper,
                        responseWrapper,
                        generalException);
            }
        }
        if (body.isSet()) {
            body.serializeTo(httpResponse, serializerChain, httpRequest);
        } else if (chain != null) {
            chain.doFilter(httpRequest, httpResponse);
        }
    } //End of MatcherFilter.doFilter()```

**Comment by perwendel** [comment]
Sorry for not having reviewed this earlier. It's hard taking care of all incoming PRs. This is a highly requested feature. I will review the PR this week.

**Comment by perwendel** [comment]
Again sorry. There has been too much shit too take care of the last couple of weeks. Again, I'll review this ASAP and when done I plan to release a new version of Spark with this included.

**Comment by perwendel** [comment]
:+1:

**Comment by javiercanillas** [comment]
Thanks!!!!

**Pull request merged**
