### PR TITLE
Fix for issues 722 and 723 +comments

### PR DESCRIPTION
**Pull request by fdmoulin**
Implements the fixes for issue https://github.com/perwendel/spark/issues/722 and trivial issue https://github.com/perwendel/spark/issues/723.  Comments have also been expanded.

This new version should now gracefully handle exceptions thrown in custom error page routes and fallback to the default error pages when needed.

### CODE REVIEW

**Comment by paul-hammant** [comment]
There is not test for this, and it seems like there could be quite easily for those super familiar with the problem @fdmoulin :)

GenericIntegrationTest.java is probably where :)

**Comment by tipsy** [comment]
@fdmoulin Could you update this?

**Comment by fdmoulin** [comment]
Sure, I'll take a look at it as soon as I get a chance.

**Comment by tipsy** [comment]
Pinging @fdmoulin

**Comment by fdmoulin** [comment]
Resolved conflicts and updated.

**Comment by tipsy** [comment]
Great @fdmoulin, thanks!

**Pull request merged**
