### PR TITLE
Rename from 'done' to 'afterAfter' (better name wanted)

### PR DESCRIPTION
**Pull request by perwendel**
Name change from 'done' do 'afterAfter' since 'done' is not really describing the functionality. We'd like to use 'finally' but it's a java keyword.

### CODE REVIEW

**Comment by MouettE-SC** [comment]
For the sake of completion I'd suggest renaming the DoneFilters class to AfterAfterFilters and the HttpMethod enum value from done to afterAfter. I can do a quick PR if you wish.

**Comment by yuj** [comment]
if you wanted "finally" but couldn't due to reserved keyword, then how about "lastly"

**Comment by tipsy** [comment]
Lastly was considered, but it just doesn't feel right:
`before`, `after`, `lastly` 🤔

**Comment by ledinscak** [comment]
What about the name "atLast"

**Pull request merged**
