### PR TITLE
Make bodyContent available in the after filters

### PR DESCRIPTION
**Pull request by kliakos**

### CODE REVIEW

**Comment by kliakos** [comment]
@perwendel can you please revisit thir PR?

It is very important for logging and response manipulation. And it is actually something documented as a feature, while it is not working.

**Comment by briannesbitt** [comment]
:+1:

**Comment by angexis** [comment]
:+1:

**Comment by kliakos** [comment]
This PR is obsolete, issue has been fixed in the latest version.

**Pull request closed without merging**
