### PR TITLE
programmatic access to server access log configuration

### PR DESCRIPTION
**Pull request by mitranc**
Hi Guys,

This is about allowing Spark to configure the  embedded Jetty Server access logs as documented here
http://www.eclipse.org/jetty/documentation/current/configuring-jetty-request-logs.html#implementing-request-log

I need to be able to configure native logging without having to go with the workaround described in this stackoverflow article
http://stackoverflow.com/questions/30039568/spark-web-framework-logging-requests-and-responses

Can you please review and release this as soon as possible? 
I work behind a proxy with strict rules and it would be nice to download the updated version as a dependency from maven central instead of working with a local patch.

Many Thanks,
Connie

### CODE REVIEW

**Comment by ygaller** [comment]
@mitranc I think this may be similar to a PR I submitted a while back: https://github.com/perwendel/spark/pull/726 . Would be great to have a request log available...

**Comment by mitranc** [comment]
I've just pushed an integration test using NCSARequestLog and a mock log file looking like this:
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  16
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  1
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  1
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  1
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  0
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  0
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  1
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  1
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  0
127.0.0.1 - - [07/Apr/2017:19:27:28 +0000] "GET //localhost:33315/hi HTTP/1.1" 200 12  0

Jetty provides an implementation called NCSARequestLog which supports the NCSA format in files that will roll over on a daily basis.

The Logback Project offers another implementation of a RequestLog interface, providing rich and powerful HTTP-access log functionality.

With this pull request it would also be possible to define a custom request logger by implementing Jetty’s RequestLog.java interface and plugging it in similar to the NCSARequestLog, as done in the integration test I've provided.

Hope this is helpful.

**Comment by tipsy** [comment]
Was this solved by #813 @mitranc @ygaller ?

**Comment by mitranc** [comment]
Ok - #813 allows configuring the log file and that is what i was looking for.
I'll close this pull request.
@tipsy @ygaller   Any idea when this will be released?

Thanks,
C

**Comment by tipsy** [comment]
@mitranc We're trying to get it done during easter.

**Pull request closed without merging**
