### PR TITLE
Add routes/filters that take just request, just response, and neither:

### PR DESCRIPTION
**Pull request by tipsy**
- RequestRoute: handle(request)
- ResponseRoute: handle(response)
- EmptyRoute: handle()
- RequestFilter: handle(request)
- ResponseFilter: handle(response)
- EmptyFilter: handle()

Also, overload get/post/before/after with Request/Empty Route/Filter for lambdas

### CODE REVIEW

**Comment by bademux** [comment]
Just curious, why to not let OOP to do the job? 
Just leave generic Route\Filter methods like `public static void get(String path, Route route)`
Imho, the Spark is greate cos it simple there is no need in complication by adding RequestRoute\RequestFilter it can be done on user side if needed.

**Comment by tipsy** [comment]
The commit mostly just adds some simple boilerplate and overloads. Are you worried that having these extra interfaces will confuse users? 

Being able to do:

```
get("/hello", () -> "Hello");
get("/hello", req -> "Hello");

EmptyRroute route = () -> {
   // Whatever is returned is independent of request/response
}

RequestRoute route = (Request req) -> {
   // Whatever is returned depends only on request
}
```

Is good for conveying the intent of the programmer, and it makes it a lot easier to read for someone who is unfamiliar with the code.

It's hard to draw a line between what users should implement themselves and what should be in the framework, but in this case I don't see how anyone would implement it themselves without adding a big chunk of non-project code to their projects.

**Comment by bademux** [comment]
Thanks for the answer!
In my opinion KISS for Spark is the 1st target - we already had Spring.

Referring to #513, `get("/hello", () -> "Hello")` can be implemented with standard `Supplier<T>` and additional method in builder.

```java
class Route{
 static class Builder{
   ...
   static Buider buildGet(String path, Supplier<String> handler){
     handler = (req, resp) -> handler.get();
   }

   Builder accept(MimeType type){...}

   //allows to "clone" similar routes
   Route toBuilder(){}
 }
}
```

**Comment by tipsy** [comment]
Will not be added to core.

**Pull request closed without merging**
