### PR TITLE
Enhancement: concept of "finally" filter 

### PR DESCRIPTION
**Pull request by gutobortolozzo**
It runs in the finally clause of MatcherFilter, so it give you the guarantee of the filter will be executed even if exception is thrown.

Can you provide me some feedback about this code, and if its contemplate the whole idea discussed on issue #195 ?

### CODE REVIEW

**Comment by kodfodrasz** [comment]
This one is needed badly!

**Comment by basdek** [comment]
I agree with @kodfodrasz that we need this one badly (or anything that can provide us with such a thing, perhaps another solution is more middleware like exception handling). 

I can see something like this work:

```

Spark.exception(Exception.class, (e, req, res) -> {
 //do all things finally / transactiony;
}

Spark.exception(MySpecificExceptionThatNeedsSpecificResponseHandling.class, (e,req,res) -> {
}

```

**Comment by kodfodrasz** [comment]
@basdek  I think a finally clause would be better, as it would be idiomatic with the java exception handling mechanism, and because it would enable more concise code, and it wouldn't need the knowledge of Spark internals (like halt is handled by a special exception type).

**Comment by basdek** [comment]
@perwendel  @gutobortolozzo How can we help fixing this? And if @gutobortolozzo, is not able to finish it, can we continue working this PReq, perhaps via a fork of your repo?

**Comment by gutobortolozzo** [comment]
@basdek @kodfodrasz I willing to start working again in this PR, since more people need it, probably tomorrow I will take a look at my one year old code and see if it keep working after a merge with master code :) 
If you have any suggestion, it would be welcome.

@perwendel Any thoughts about this feature? What's your opinion about a finally filter?

**Comment by kodfodrasz** [comment]
great news! I'm looking forward to having it in spark! :+1:

**Comment by gutobortolozzo** [comment]
#406

**Comment by basdek** [comment]
@gutobortolozzo Thank you for this awesome work man! (Will be checking into it as soon as my meetings are over today)

**Pull request closed without merging**
