### PR TITLE
Split project into "core" and "embedded".

### PR DESCRIPTION
**Pull request by jakaarl**
Reorganized project into core and embedded, and a parent aggregator project. Removed Jetty dependency from core part.

### CODE REVIEW

**Comment by jakaarl** [comment]
It's been months without a reaction. @perwendel @tipsy anyone? I would imagine this is useful, since it 1) eliminates Jetty dependency for those who don't need it, 2) shrinks the deployable WAR considerably, 3) possibly makes it a bit easier to manage Jetty version changes and 4) paves way for other embedded server implementations.

**Comment by tipsy** [comment]
This is a massiv change, both technically (nice work!) and strategically. We'll have to see what @perwendel thinks. I'll nag him personally if he doesn't respond soon.

**Comment by atorstling** [comment]
+1 on this one. I would like to implement deployment using programmatic servlet apis, and eliminate the static state for deployment in other servers. This PR would pave the way nicely.

**Comment by jakaarl** [comment]
Ugh, things got a bit messy... redoing this.

**Comment by jakaarl** [comment]
Replaced by #781.

**Pull request closed without merging**
