### PR TITLE
Hide Jetty version in response headers by default #200

### PR DESCRIPTION
**Pull request by gutobortolozzo**
Providing HttpConnectionFactory injection point to configure embedded jetty.

### CODE REVIEW

**Comment by tipsy** [comment]
@gutobortolozzo The title doesn't seem to reflect the code changes. What is this really supposed to do?

**Comment by gutobortolozzo** [comment]
@tipsy It was supposed to allow `HttpConnectionFactory` to be configurable and allow developers to call something like `httpConnectionFactoryfactory.getHttpConfiguration().setSendServerVersion(false);`

**Comment by tipsy** [comment]
Oh, I see. It's really that complicated to remove the header, huh.. Would it be simpler to just set `setSendServerVersion(false)` directly instead of allowing devs to configure it?

**Comment by gutobortolozzo** [comment]
@tipsy It is one possible approach. My idea to expose `HttpConnectionFactory` came mainly because `HttpConfiguration` has several other configuration methods that would be nice to expose but add it to Spark seems like a burden, IMHO.

**Comment by tipsy** [comment]
> What is your opinion about this?
I think you make a very valid point. We want to keep Spark's API as simple as possible, so doing configuration through `HttpConfiguration` seems to be a lot better than exposing individual methods. This PR needs to be renamed though. If you update it I'll see if I grab @perwendel for a quick chat and merge it.

**Comment by tipsy** [comment]
> @perwendel says:
> For the "main" API (Spark class) we should have generic and often used config, like threadPool etc.
> Other web-server specific config should be done via EmbeddedServers (which is not yet ready for this). Ie, they would have to provide configuration to the current used embedded server or the one they want to change it with. e.g.
> `EmbeddedJettyServerFactory.configuration(...)`

So, we can't use this approach. Hm. Keeping the PR open though.

**Comment by gutobortolozzo** [comment]
@tipsy I will take a look at those classes and see how I can configure Jetty using them to post a new PR.

**Comment by tipsy** [comment]
This should be taken care of by #813

**Pull request closed without merging**
