### PR TITLE
Fixed bug where null responses were being handled as not matched routes

### PR DESCRIPTION
**Pull request by MartinsThiago**
Here's one more

### CODE REVIEW

**Comment by AzureusNation** [comment]
Looks like you've broken 11 tests. They will need fixing.

**Comment by MartinsThiago** [comment]
Hmmm... After I forked the project i saw they were breaking already

It's not an excuse, but the weirdo is running these tests where spark is
ignited separately the tests passes :(

**Comment by MartinsThiago** [comment]
If today I have time I'll try to investigate why it's behaving this way

**Comment by MartinsThiago** [comment]
Whooops... I ran the tests through maven then I saw those error.

I ll submit a fixed PR, sorry :sweat_smile:

**Pull request closed without merging**
