### PR TITLE
Exception and route handle fixed: #349 

### PR DESCRIPTION
**Pull request by Tradunsky**
According to pull request #349 for avoiding route missing when exception thrown and handled I've implemented enum of response state.
It also fixed the error of processing response without content, e.g. 204

dev note:
broken jtests fixed too

### CODE REVIEW

**Comment by Tradunsky** [comment]
Those changes also should fix the issue
https://github.com/perwendel/spark/issues/335

**Comment by perwendel** [comment]
tx for contributing.

PR is not up to date with master.
Import order is messed up (and formatting in some places) which makes otherwise unchanged files being part of the PR.

Please format according to formatter in https://github.com/perwendel/spark/tree/master/config.

Also remove modifications to just logs that are not related to this fix. It makes it harder to review.

**Comment by elanhami** [comment]
Any news regarding this?

**Comment by perwendel** [comment]
@elanhami I'm waiting for an updated PR.

**Comment by tipsy** [comment]
@Tradunsky any plans to update this?

**Comment by Tradunsky** [comment]
@tipsy Sorry, I have no intention to support long-live MR. I've faced so many troubles with Spark, so I just replaced it with more stable framework in my app. As for now, Spring 5 looks pretty similar to functional approach.

**Comment by tipsy** [comment]
Fair enough!

**Pull request closed without merging**
