### PR TITLE
Make Jetty servers tunable

### LINKED ISSUE #796: Form too Large Exception / org.eclipse.jetty.server.Request
request.attribute("org.eclipse.jetty.server.Request.maxFormContentSize", 603169);
invalid

### PR DESCRIPTION
**Pull request by gquintana**
Fixes #796  #314
Adds an extension to let people configure their Jetty Server

### CODE REVIEW

**Comment by tipsy** [comment]
Interesting, I'll have a look in the weekend.

**Comment by gquintana** [comment]
I did as few changes as I could.

To go further, one could make the JettyServerFactory more generic: configure the connectors and so forth.
I would require passing more arguments (port, address, ssl...)

**Comment by tipsy** [comment]
@gquintana Looks good to me, trying to get a hold of the elusive @perwendel so he can OK this.

**Comment by perwendel** [comment]
I'll check this soon. My insane period of intense workload is (hopefully) over.

**Comment by perwendel** [comment]
Did a quick review and it looks good. I'll do a more thorough review soon and then merge.

**Comment by perwendel** [comment]
Good stuff!!!
:+1:

**Pull request merged**
