### PR TITLE
Adding 404 and 500 custom page error

### PR DESCRIPTION
**Pull request by debarshri**
Added a ExceptionUtil for adding custom 404 and 500 error pages.

### CODE REVIEW

**Comment by martylamb** [comment]
This is nice.  I'm not yet familiar with this code flow but is there any reason not to provide arbitrary error page handlers rather than specific 404 and 500 handlers?

something like:

```java
    // other spark setup
   halt(500, new My500HaltHandler());
   halt(404, new NotFoundHandler());
   halt(new DefaultErrorHandler()); // is used if no status-code specific handler is specified
```

**Comment by debarshri** [comment]
It has been pretty longtime..I even forgot what it was actually about..Let me take alook!

**Comment by debarshri** [comment]
So..the thing that I have tried to solve is when a you have a route which is not specified in the list of routes..it redirects to a error page. I think you cannot do that with halt. 

To be more specific.

Lets assume you have declared routes /route1 and /route2, but client requests for /route3, then it should be redirected to error pages.

It is related to issue https://github.com/perwendel/spark/issues/54

**Comment by mnrasul** [comment]
Good effort. Thanks. 
The thing is there are all kinds of errors which one would like to handle. The current implementation is fairly restrictive. Can it be made more generalized?

**Comment by OzzyTheGiant** [comment]
To @mnrasul and anyone who wants to handle multiple errors at once, my approach was to do a catch all exception function:

```java
public static void main(String[] args) {
        // all other code here
       
       exception(Exception.class, exceptionHandler);
}

public static ExceptionHandler<Exception> exceptionHandler = (exception, request, response) -> {
	var statusCode = 500; // default status code
	var errorMessage = exception.getMessage(); // default error message to output
	
	if (exception instanceof HttpException) {
		HttpException httpException = (HttpException) exception;
		statusCode = httpException.getStatusCode();
		errorMessage = httpException.getMessage();
	}
	response.status(statusCode);
	response.body(String.format("{\"message\": \"%1$s\"}", errorMessage));
};
```

 I created a generic HttpException class for all http errors that can occur in app (400, 404, 500, etc.)
 Each http exception will have it's own sub class (example: BadRequestError for 400), although you may want to name them something more specific for logging purposes, but when instantiating a new exception, the constructor will call super() for HttpException with the message and a status code. This is done so that you don't have to do an `instanceof` check for every error class, just for HttpException. If the exception in question is not an instance of HttpException, it will simply just get the message from that exception class. The HttpException class could look like this:

```java
import java.io.IOException;

public class HttpException extends IOException {
	private static final long serialVersionUID = 1L;
	private static String defaultMessage = "Server Error: Please try again";
	protected int code = 500;

	public HttpException() {
		super(defaultMessage);
	}

	public HttpException(String message) {
		super(message);
	}

	public HttpException(String message, int code) {
		super(message);
		this.code = code;
	}

	public int getStatusCode() {
		return this.code;
	}
}
```

Perhaps this could be added either to docs or as part of a tutorial in the Tutorials web page

**Pull request closed without merging**
