### PR TITLE
Added Internal Redirect Feature

### PR DESCRIPTION
**Pull request by QuackMartins**
PR about #386

### CODE REVIEW

**Comment by MartinsThiago** [comment]
Improved redispatcher implementation, now it uses the same logic as MatchFilter

**Comment by sepatel** [comment]
Any further progress on this? Is a really helpful feature that I'm looking for in order to help support backwards compatibility as we refactor the web service API's and help migrate people over to the new API's without breaking them outright.

**Comment by MartinsThiago** [comment]
@sepatel I don't know if this PR is going to be merged soon, but if you really need this feature...
You can use it with [jitpack.io](https://jitpack.io/#martinsthiago/spark/2.4)

**Comment by sepatel** [comment]
I'm a bit confused. The jitpack link is for version 2.4.0. The latest version is 2.6.0.RC0. Currently I'm using 2.5.5 and was planning to move over to 2.6.0 once it is properly released.

Is this something that will be part of 2.6.0 when properly released? If so then I can hold off a bit and wait for that probably as I still have another 3 weeks before this update hits production.

**Comment by tipsy** [comment]
> Is this something that will be part of 2.6.0 when properly released?
No, we won't add anything new to the RC (unless it's very very small), just fix bugs.

**Comment by sepatel** [comment]
So is it then a fork of the 2.4.x codebase? If so then I will probably be better of sticking with the hack I'm doing to try and redirect the responses around. What release is it scheduled for? I'm presuming then it would fall under a potential 2.7.x release? Do you have a snapshot of that upcoming release then or a fork of the 2.6.0 codebase this feature might be a part of? Obviously I don't want to be losing the features I've gained when I upgraded from 2.4 to 2.5 and I am looking forward to some of the newer 2.6 features as well.

**Pull request closed without merging**
