### PR TITLE
Added SparkApplication.destroy() Fixes #151 

### LINKED ISSUE #151: SparkApplication.destroy()
SparkApplication has init() method but not destroy(). This listener is needed on some use cases.

### PR DESCRIPTION
**Pull request by zeroflag**
I added the destroy() method to the SparkApplication interface with "default" modifier.

### CODE REVIEW

**Comment by shauvik** [comment]
+1 

I need his as well. I'm using a service that starts a background network thread (aws-sdk-s3) and I need to shut the service ondestroy to avoid a memory leak. [ref](http://stackoverflow.com/a/20632949/227556)

**Comment by perwendel** [comment]
I will have a look at this after my vacation (the week after next)

**Comment by vadyalex** [comment]
Thank you @zeroflag! Very useful fix. Looking forward to see in in master. 😌

**Comment by perwendel** [comment]
Very nice!!! Merged!

**Comment by zeroflag** [comment]
Cool, thanks!

**Pull request merged**
