### PR TITLE
#570 Fix: Static instance of ExceptionMapper. 

### PR DESCRIPTION
**Pull request by vzamanillo**
Per service ExceptionMapper.

### CODE REVIEW

**Comment by jakaarl** [comment]
I haven't really looked into the reasoning/logic of this, but on a superficial level, this looks good to me. So the idea is, that it's per `Servlet` or per `Service`, depending on if being run in embedded or deployed mode? @vzamanillo could you resolve the conflicts?

**Comment by vzamanillo** [comment]
@jakaarl, I don't remember the applied logic actually, the PR is very old and I need to be review it. The merge conflicts are resolved.

**Comment by melges-morgen** [comment]
Hi, does anybody looking on it? I am faced with bug which should be fixed by this PR and it would be great if it will be merged.

**Comment by vzamanillo** [comment]
The PR is ready to be merged.

**Pull request closed without merging**
