### PR TITLE
Reducing boilerplate code rethrowing exceptions in tests

### PR DESCRIPTION
**Pull request by wojtek-szymanski**
Hi Guys,

This PR contains a quick introduction how to easily improve your tests quality.

What about frameworks like AssertJ/Mockito/JUnitParams, do you consider those test dependencies at all? 
If so I have great candidates for this: `spark.RequestTest` and `spark.QueryParamsMapTest`

### CODE REVIEW

**Comment by travisspencer** [comment]
Writing unit tests is a lot easier with Mockito et. al. I'd find it easier to write tests with these, and would ask that the maintainers accept a dependency on them, especially if @wojtek-szymanski is willing to refactor the existing tests to use them.

**Comment by drabiter** [comment]
+1

**Comment by wojtek-szymanski** [comment]
Sure, I will be waiting for your decision.

**Comment by perwendel** [comment]
Manual merged in #328

**Pull request merged**
