### PR TITLE
 #448 Implementation to read dynamic path parameters

### PR DESCRIPTION
**Pull request by alissonbrunosa**
Example usage

``` java
import static spark.Spark.*;

public class HelloWorld {
    public static void main(String[] args) {
        get("/hello/:name.json", (request, response) -> {
            return "Hello: " + request.params(":name");
        });
    }
}
```

### CODE REVIEW

**Comment by tipsy** [comment]
@alissonbrunosa could you elaborate/specify what this solves (and changes)?

**Comment by alissonbrunosa** [comment]
Hi @tipsy 
If you check the issue #448, you can see what this PR solves.
The main idea is to allow the user to specify and read dynamic path.
You can check the example in the PR as well.

**Comment by tipsy** [comment]
@alissonbrunosa Dynamic path params are already support via `:param`. This PR seems to allow adding file-extensions to path-params, but in which cases is that useful?

If you just do `request.params("name.json")` you will get the value you need, and if you do `request.params("name.json").split(".json")[0]` you will replicate what your PR does, correct?

I'm not seeing a big need for this, and I'm worried that it might cause unexpected behavior 🤔

**Comment by alissonbrunosa** [comment]
@tipsy You're completely correct.
I've just added this feature because **Spark** is inspired by Sinatra. If you take a look at Sinatra, you'll see it has this feature.

**Comment by tipsy** [comment]
Ah, I'll all it do the v3 then!

**Pull request closed without merging**
