### PR TITLE
Some refactors done

### PR DESCRIPTION
**Pull request by Ariel-Isaacm**
-AbstractResource.java  Added some Try-with-resource
-SimpleRouteMatcher.java {  
"Arrays.asList(routeEntry.acceptedType)" Always returns a list with a single element, so a SingletonList is the best way to go
"new RouteMatch(routeEntry.target, routeEntry.path, path, acceptType)" acceptType is always null
}
-GzipUtils.java simplified return statement
-IOUtils.java Redundant statement
-MimeParse.java Changed to a StringBuilder and optimized the append statements
- JettySparkServer.java webSocketServletContextHandler null check is done before, so there's no point checking it again.
  -StaticFilesTest.java since tmpExternalFile.delete(); returns a boolean if the File was deleted, I added some more information

### CODE REVIEW

**Comment by perwendel** [comment]
Tx for contrib. 

Before proper reviewing the following needs to be fixed:
* import order and policy don't comply with Spark standars. 
* Code formatting is not compliant with Spark standards in some places.

See: https://github.com/perwendel/spark/tree/master/config for intellij formatter.

**Comment by Ariel-Isaacm** [comment]
Hi @perwendel 
When i try to execute the jar tells me that the jar file is corrupted any thoughts on this?

**Comment by perwendel** [comment]
@Ariel-Isaacm 
You should import it under 'Import settings' in intellJ menu.

**Comment by Ariel-Isaacm** [comment]
I applied the formatter to the code and it formatted more files that the ones i modified, i think it shouldn't have any trouble.

**Pull request closed without merging**
