### PR TITLE
Fixed bug where null responses were being handled as not matched routes

### PR DESCRIPTION
**Pull request by MartinsThiago**
Fixed previous pr -> #637

### CODE REVIEW

**Comment by MartinsThiago** [comment]
`echo 'Hey o/... dont forget this one'`

**Comment by tipsy** [comment]
@perwendel is on an offline vacation. He will start merging changes around the end of the month.

**Comment by MartinsThiago** [comment]
Oops, sorry :)

**Comment by MartinsThiago** [comment]
Got the idea

I saw some pull requests with same intention... So I vote for achieving empty responses with null even cause `""` are not trully trully empty

Sometime ago I got confused because a created a route (returning null) and I was not understanding why logs were telling me no route was matched and I saw the route being executed while debugging

**Comment by MartinsThiago** [comment]
So... In summary I agree that spark should rely on `response.body` but for routes I think we should rely on `match`

**Comment by perwendel** [comment]
I'll think about it :)

**Comment by MartinsThiago** [comment]
Nice... I am closing this pull

Anything call me o/

**Pull request closed without merging**
